export { ReactComponent as ChevronDownSvg } from './chevron-down.svg'
export { ReactComponent as LogoSvg } from 'src/assets/icons/shopee.svg'
export { ReactComponent as GlobalSvg } from 'src/assets/icons/global.svg'
export { ReactComponent as SearchSvg } from 'src/assets/icons/search.svg'
export { ReactComponent as CartSvg } from 'src/assets/icons/cart.svg'
export { ReactComponent as LoadingSvg } from 'src/assets/icons/loading.svg'
